pipeline:
  name: js
  identifier: js
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702454246010
        repoName: NavjitK/SampleApp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
